Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: nodejs8.10

Parameters:
    SamMultipler:
        Description: "SAM multiplier. Make this really big to have a party :)"
        Type: "String"
    OriginUrl:
        Description: "The origin url to allow CORS requests from. This will be the base URL of your static SAM website."
        Type: "String"
Resources:
    GetSAMPartyCount:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            CodeUri: ./
            Environment:
                Variables:
                    SAM_MULTIPLIER: !Ref SamMultipler
                    ORIGIN_URL: !Ref OriginUrl
            Tracing: Active
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /sam
                  Method: get
                  RestApiId: !Ref TheApiGateway
    TheApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: 'Prod'
            MethodSettings:
                - HttpMethod: '*'
                  ResourcePath: /*
                  LoggingLevel: "INFO"
                  MetricsEnabled: true
                  DataTraceEnabled: true

    CloudWatchRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                 - Effect: Allow
                   Principal:
                    Service:
                     - "apigateway.amazonaws.com"
                   Action: "sts:AssumeRole"
                Path: "/"
                ManagedPolicyArns:
                 - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
    Account:
        Type: AWS::ApiGateway::Account
        Properties:
            CloudWatchRoleArn:
             "Fn::GetAtt":
              - CloudWatchRole
              - Arn